"""First migration

Revision ID: 171f39997f32
Revises: 
Create Date: 2021-07-01 07:51:43.641297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171f39997f32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messworks_tag_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messworks_tag_description')
    # ### end Alembic commands ###
